---
title: "project2"
output: html_document
date: "2023-12-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Research Questions:

1. How does Co2 production correlate with population of a country?


2. How does Co2 production in different countries in 1990 differ from 2021?


3. How does the Human Development Index (HDI) compare with the population of a country?


4. How does HDI compare with Co2 production for countries in 2021?

```{r}
library(readr)
co2 <- read_csv("../../../../../../Downloads/co2_production.csv")
hdi <- read_csv("../../../../../../Downloads/human_development_index.csv")
pop <- read_csv("../../../../../../Downloads/World-population-by-countries-dataset.csv")
```

```{r}

library(tidyverse)
new_names <- sub("co2_prod_", "", names(co2))
names(co2) <- new_names
co2l <- co2 %>% pivot_longer(!c("ISO3", "Country", "hdicode", "region", "hdi_rank_2021"),
                             names_to = "Year",
                             values_to = "CO2 Production")

pop <- pop %>% 
  rename(Country = "Country Name")


popl <- pop %>% pivot_longer(!c("Country", "Country Code"),
                     names_to = "Year",
                     values_to = "Population")
```

```{r}
co2l2 <- co2l[, names(co2l) %in% c("Year", "CO2 Production", "Country")]
popl2 <- popl[, names(popl) %in% c("Year", "Country", "Population")]
cpmerge <- inner_join(co2l2, popl2, by = c("Year", "Country"))

new_n <- sub("hdi_", "", names(hdi))
names(hdi) <- new_n

hdil <- hdi %>% pivot_longer(!c("ISO3", "Country", "hdicode", "region", "rank_2021"),
                             names_to = "Year",
                             values_to = "HDI")
hdil2 <- hdil[, names(hdil) %in% c("Year", "HDI", "Country")]
```

```{r}
merge <- inner_join(cpmerge, hdil2, by = c("Year", "Country"))

merge <- merge %>% 
  filter(!(Country == "World" | Country == "South Asia" | Country == "Sub-Saharan Africa"))

merge <- merge %>% 
  mutate(CO2Index = ifelse(`CO2 Production` <= 22, 
    "Low", ifelse(`CO2 Production` > 22 & `CO2 Production` < 44, "Middle", "High")))

merge <- merge %>% 
  mutate(Year = as.numeric(Year))

merge <- merge %>% 
  group_by(Country) %>% 
  mutate(AvgCO2 = mean(`CO2 Production`, na.rm = TRUE)) %>% 
  mutate(AvgPop = mean(Population, na.rm = TRUE))


write_csv(merge, "Merged_data.txt")
```

```{r}
merge <- read_delim("Merged_data.txt")
```


## Question 1


```{r}
library(maps)
world <- map_data("world") %>% 
  mutate(region = ifelse(region == "USA", "United States", region)) %>% 
  mutate(region = ifelse(region == "Russia", "Russian Federation", region))

mapping <- function(input_year){
  data_map <- world %>% 
    mutate(Country = region) %>% 
    merge(merge %>% filter(Year == input_year), by = "Country", all.x = TRUE) %>% 
    group_by(group) %>% 
    arrange(order)
  
  co2map <- ggplot(data_map, aes(long, lat, group=group, fill=`CO2 Production`)) +
    geom_polygon(col="black", linewidth=0.3) +
    scale_fill_continuous(low = "cadetblue1", high = "blue4", limits = c(0,60), labels = scales::label_number_si()) +
    scale_y_continuous(breaks = c()) +
    scale_x_continuous(breaks=c()) +
    theme_void() +
    coord_quickmap()
    
  avgpopmap <- ggplot(data_map, aes(long, lat, group=group, fill=`Population`)) +
    geom_polygon(col="black", linewidth=0.3) +
    scale_fill_continuous(low = "cadetblue1", high = "blue4", limits = c(0, 2*10^9), labels = scales::label_number_si()) +
    scale_y_continuous(breaks = c()) +
    scale_x_continuous(breaks=c()) +
    theme_void() +
    coord_quickmap()

  assign("co2map", co2map, envir = parent.frame())
  assign("avgpopmap", avgpopmap, envir = parent.frame())
}

library(gridExtra)

```
### 2021
```{r}
mapping(2021)
grid.arrange(co2map, avgpopmap, heights=c(6,6), ncol=1)
```


## Question 2

```{r}
merge %>% 
  filter(Year %in% c(1990, 2021)) %>% 
  filter(Country %in% c("Nigeria", "United States", "Brazil", "Australia", "France", "China")) %>% 
  group_by(Country, Year) %>% 
  ggplot(aes(Country, `CO2 Production`, fill = factor(Year))) +
  geom_col(position = "dodge", col = "black") +
  labs(title = "CO2 Production in 1990 vs. 2021", fill = "Year") 
  
```

## Question 3

```{r}
mergesum <- merge %>%
  group_by(Country) %>%
  summarise(avghdi = mean(HDI, na.rm = TRUE),
            avgpop2 = mean(Population, na.rm = TRUE))

ggplot(mergesum, aes(avgpop2, avghdi, col = Country)) +
  geom_point(size = 3, show.legend = FALSE) +
  labs(x = "Population", y = "Human Development Index (HDI)", title = "Population vs. Human Development Index (HDI)") + 
  geom_smooth(method = lm, se = FALSE, show.legend = FALSE, col = "red") +
  scale_x_continuous(labels = scales::label_number_si())
```

## Question 4

```{r}
merge %>% 
  filter(Year == "2021") %>% 
  ggplot(aes(`CO2 Production`, HDI, col = Country)) +
  geom_point(size = 3, show.legend = FALSE) +
  labs(title = "CO2 Production vs. HDI in 2021") +
  geom_smooth(show.legend = FALSE, se = FALSE, col = "black")
```


